name: cripto_currency_app_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  dio: ^4.0.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.1+1
  shared_preferences: ^2.0.15
  toggle_switch: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_native_splash: ^2.2.7
  loading_animation_widget:
  cloud_firestore:
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  image_path: "assets/images/bitcoin.png"
  android: true
  ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#231f2d"
  image: "assets/images/bitcoin.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
